# Development connection
development:
  adapter: mysql2
  database: bubbleStream
  username: root
  password: "12345678"
  host: localhost

# Test connection
test:
  adapter: mysql2
  database: bubbleStrem
  username: root
  password: ""
  host: localhost

# Productionconnection
production:
  adapter: mysql2
  database: bubbleStrem
  username: root
  password: ""
  host: localhost
